INSERT INTO movies (tmdb_id, title, slug, year, genres, poster_path_remote, summary, director, cast, duration, rating, rating_count)
VALUES
    (27205, 'Inception', 'inception-2010', 2010, JSON_ARRAY('Science Fiction', 'Action'), '/9gk7adHYeDvHkCSEqAvQNLV5Uge.jpg', 'Un ladro capace di infiltrarsi nei sogni viene incaricato di impiantare un''idea nella mente di un magnate.', 'Christopher Nolan', JSON_ARRAY('Leonardo DiCaprio', 'Joseph Gordon-Levitt', 'Elliot Page'), 148, 8.3, 32000),
    (238, 'Il padrino', 'il-padrino-1972', 1972, JSON_ARRAY('Crime', 'Drama'), '/3bhkrj58Vtu7enYsRolD1fZdja1.jpg', 'La saga dei Corleone racconta l''ascesa e la trasformazione del potere criminale in America.', 'Francis Ford Coppola', JSON_ARRAY('Marlon Brando', 'Al Pacino', 'James Caan'), 175, 9.2, 42000),
    (603, 'Matrix', 'matrix-1999', 1999, JSON_ARRAY('Action', 'Science Fiction'), '/f89U3ADr1oiB1s9GkdPOEpXUk5H.jpg', 'Thomas Anderson scopre la vera natura della realtà e abbraccia il suo destino come Neo.', 'Lana Wachowski', JSON_ARRAY('Keanu Reeves', 'Carrie-Anne Moss', 'Laurence Fishburne'), 136, 8.2, 28000),
    (155, 'The Dark Knight', 'the-dark-knight-2008', 2008, JSON_ARRAY('Action', 'Crime'), '/qJ2tW6WMUDux911r6m7haRef0WH.jpg', 'Batman affronta il Joker, un genio criminale che getta Gotham nel caos.', 'Christopher Nolan', JSON_ARRAY('Christian Bale', 'Heath Ledger', 'Aaron Eckhart'), 152, 9.0, 50000),
    (1891, 'Il favoloso mondo di Amélie', 'il-favoloso-mondo-di-amelie-2001', 2001, JSON_ARRAY('Romance', 'Comedy'), '/wnUAcUrMRGPPZUDroLezhz7kwR7.jpg', 'Amélie decide di dedicarsi a migliorare la vita degli altri mentre scopre l''amore.', 'Jean-Pierre Jeunet', JSON_ARRAY('Audrey Tautou', 'Mathieu Kassovitz'), 122, 8.0, 17000),
    (424, 'Schindler''s List', 'schindlers-list-1993', 1993, JSON_ARRAY('Drama', 'History'), '/c8Ass7acuOe4za6DhSattE359gr.jpg', 'Oskar Schindler salva centinaia di ebrei durante l''olocausto.', 'Steven Spielberg', JSON_ARRAY('Liam Neeson', 'Ben Kingsley', 'Ralph Fiennes'), 195, 8.6, 25000),
    (680, 'Pulp Fiction', 'pulp-fiction-1994', 1994, JSON_ARRAY('Crime', 'Drama'), '/d5iIlFn5s0ImszYzBPb8JPIfbXD.jpg', 'Storie intrecciate di criminali, gangster e un misterioso valigetta a Los Angeles.', 'Quentin Tarantino', JSON_ARRAY('John Travolta', 'Samuel L. Jackson', 'Uma Thurman'), 154, 8.9, 47000),
    (299536, 'Avengers: Infinity War', 'avengers-infinity-war-2018', 2018, JSON_ARRAY('Action', 'Adventure', 'Science Fiction'), '/7WsyChQLEftFiDOVTGkv3hFpyyt.jpg', 'Gli Avengers affrontano Thanos in una battaglia per il destino dell''universo.', 'Anthony Russo, Joe Russo', JSON_ARRAY('Robert Downey Jr.', 'Chris Hemsworth', 'Scarlett Johansson'), 149, 8.4, 62000),
    (496243, 'Parasite', 'parasite-2019', 2019, JSON_ARRAY('Thriller', 'Drama'), '/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg', 'Una famiglia povera si infiltra nella vita di una famiglia ricca con conseguenze imprevedibili.', 'Bong Joon-ho', JSON_ARRAY('Song Kang-ho', 'Lee Sun-kyun', 'Cho Yeo-jeong'), 132, 8.5, 38000),
    (278, 'Le ali della libertà', 'le-ali-della-liberta-1994', 1994, JSON_ARRAY('Drama'), '/9O7gLzmreU0nGkIB6K3BsJbzvNv.jpg', 'La storia di Andy Dufresne e della sua speranza incrollabile nel penitenziario di Shawshank.', 'Frank Darabont', JSON_ARRAY('Tim Robbins', 'Morgan Freeman'), 142, 8.7, 52000);
